### ISSUE TITLE
couldn't get the vignette on Windows

### ISSUE THREAD

**Issue by hmuranty** [timflutre/rgs3#1]
install and library loading is OK but I couldn't the vignette on Windows:

> browseVignettes("rgs3")
> No vignettes found by browseVignettes("rgs3")

**Comment by timflutre** [comment]
Thanks for the issue! Can you try this?

```
library(devtools)
install_github("timflutre/rgs3", build_vignettes=TRUE)
browseVignettes("rgs3")
```

**Comment by hmuranty** [comment]
I tried. And got an error message:

> install_github("timflutre/rgs3", build_vignettes = TRUE)
> Downloading GitHub repo timflutre/rgs3@master
> Installing rgs3
> Installing 9 packages: evaluate, formatR, highr, htmltools, knitr, mime, rmarkdown, rrBLUP, stringi
> package ‘evaluate’ successfully unpacked and MD5 sums checked
> package ‘formatR’ successfully unpacked and MD5 sums checked
> package ‘highr’ successfully unpacked and MD5 sums checked
> package ‘htmltools’ successfully unpacked and MD5 sums checked
> package ‘knitr’ successfully unpacked and MD5 sums checked
> package ‘mime’ successfully unpacked and MD5 sums checked
> package ‘rmarkdown’ successfully unpacked and MD5 sums checked
> package ‘rrBLUP’ successfully unpacked and MD5 sums checked
> package ‘stringi’ successfully unpacked and MD5 sums checked
> Warning: cannot remove prior installation of package ‘stringi’
> "C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
>   --no-restore CMD build  \
>   "C:\Users\Helene-ADMIN\AppData\Local\Temp\RtmpwxJubJ\devtools18042a4265a0\timflutre-rgs3-21ca891"  \
>   --no-resave-data --no-manual 
- checking for file 'C:\Users\Helene-ADMIN\AppData\Local\Temp\RtmpwxJubJ\devtools18042a4265a0\timflutre-rgs3-21ca891/DESCRIPTION' ... OK
- preparing 'rgs3':
- checking DESCRIPTION meta-information ... OK
- installing the package to build vignettes
- creating vignettes ...Warning: l'exécution de la commande '"C:/PROGRA~1/R/R-32~1.2/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' renvoie un statut 1
  ERROR
  Quitting from lines 289-291 (intro-rgs3.Rmd) 
  Erreur : le traitement de la vignette 'intro-rgs3.Rmd' a échoué avec le diagnostic :
  impossible d'ouvrir la connexion
  Exécution arrêtée
  Error: Command failed (1)

**Comment by timflutre** [comment]
What is your version of R? (Use `print(sessionInfo(), locale=FALSE)`.)

**Comment by hmuranty** [comment]
My version is

> R version 3.2.2 (2015-08-14)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> loaded via a namespace (and not attached):
> [1] tools_3.2.2

**Comment by timflutre** [comment]
Can you load the following packages, and redo `sessionInfo()`?
- devtools
- knitr
- rmarkdown

**Comment by timflutre** [comment]
Did you install GS3? For the vignette to work, "gs3.exe" should be available on your Windows machine (it should be named like this).

**Comment by hmuranty** [comment]
I already have these packages installed
find.package(package = c("devtools", "knitr", "rmarkdown"))
[1] "C:/Users/Helene-ADMIN/Documents/R/win-library/3.2/devtools"
[2] "C:/Users/Helene-ADMIN/Documents/R/win-library/3.2/knitr"
[3] "C:/Users/Helene-ADMIN/Documents/R/win-library/3.2/rmarkdown"

Timothée Flutre notifications@github.com a écrit :

> Can you load the following packages, and redo sessionInfo()?
> -    devtools
> -    knitr
> -    rmarkdown
>   
>   —
>   Reply to this email directly or view it on GitHub[1].
>     

## Liens:

[1] https://github.com/timflutre/rgs3/issues/1#issuecomment-170011733

**Comment by hmuranty** [comment]
Yes I have gs3.exe. Should it be in the directory from where I install
rgs3, or in the PATH ?

Timothée Flutre notifications@github.com a écrit :

> Did you installed GS3? For the vignette to work, "gs3.exe" should be
> available on your Windows machine (it should be named like this).
> 
>   —
> Reply to this email directly or view it on GitHub[1].
>       

## Liens:

[1] https://github.com/timflutre/rgs3/issues/1#issuecomment-170012754

**Comment by timflutre** [comment]
It should be in the PATH.

**Comment by hmuranty** [comment]
I copied gs3.exe in C:\Program Files\gs3 and added this directory to the PATH variable but I still have the same error message as previously.

**Comment by timflutre** [comment]
Ok, so can you try with `build_vignette=FALSE`? And then, can you try re-doing the content of the vignette (see below), so that we know what is causing the error?

Here are the commands (looks very long, but simply copy-pasting the blocks one by one should work, and the last command will show the output messages from gs3):

```
library(rgs3)

phenos.file <- system.file("extdata", "phenos_df.txt.gz", package="rgs3")
phenos <- read.table(phenos.file, header=TRUE)
phenos$year <- as.factor(phenos$year)

genos.file <- system.file("extdata", "genos_mat.txt.gz", package="rgs3")
genos <- as.matrix(read.table(genos.file))

inds <- setNames(object=1:nlevels(phenos$ind),
                 nm=levels(phenos$ind))
phenos.file.gs3 <- paste0(getwd(), "/phenos_gs3.txt")
writeDataForGs3(x=phenos, file=phenos.file.gs3,
                inds=inds, col.id=2, col.trait=3)
genos.file.gs3 <- paste0(getwd(), "/genos_gs3.txt")
writeGenosForGs3(x=genos, file=genos.file.gs3, inds=inds)

config.file <- paste0(getwd(), "/config_gs3_vce.txt")
vcs.file <- paste0(getwd(), "/var_comp_samples.txt")
sol.file <- paste0(getwd(), "/solutions.txt")
(ptl <- data.frame(position=c(which(colnames(phenos) == "year"),
                              ncol(phenos) + 1),
                   type=c("cross",
                          "add_SNP"),
                   nlevels=c(Q,
                             0),
                   stringsAsFactors=FALSE))
writeConfigForGs3(config.file=config.file,
                  data.file=phenos.file.gs3,
                  ped.file=NULL,
                  genos.file=genos.file.gs3,
                  num.loci=P,
                  method="VCE",
                  simul="F",
                  niter=2*10^4,
                  burnin=2*10^3,
                  thin=10,
                  vcs.file=vcs.file,
                  sol.file=sol.file,
                  twc=c(which(colnames(phenos) == "response"), 0),
                  num.eff=nrow(ptl),
                  ptl=ptl,
                  vc=data.frame(var=c("vara","vard","varg","varp","vare"),
                                exp=c("2.52d-04","1.75d-06","3.56","2.15","0.19"),
                                df=rep("-2", 5),
                                stringsAsFactors=FALSE),
                  rec.id=which(colnames(phenos) == "ind"),
                  cont="F",
                  mod=rep("T", nrow(ptl)),
                  ap=c(1, 10),
                  dp=c(1, 1),
                  use.mix="F",
                  blasso=FALSE)

stdouterr.file <- paste0(getwd(), "/intro_stdouterr_gs3.txt")
system.time(execGs3(config.file, stdouterr.file))
stdouterr <- readLines(stdouterr.file)
```

**Comment by hmuranty** [comment]
I get an error at

> (ptl <- data.frame(position=c(which(colnames(phenos) == "year"),
> - ncol(phenos) + 1),
> - type=c("cross",
> - "add_SNP"),
> - nlevels=c(Q,
> - 0),
> - stringsAsFactors=FALSE))
>   Error in data.frame(position = c(which(colnames(phenos) == "year"), ncol(phenos) +  : 
>   object 'Q' not found

**Comment by timflutre** [comment]
Sorry! One should add this:

```
Q <- 3        # years
I <- 500      # individuals
N <- Q * I    # measurements
P <- 4689     # SNPs
```

**Comment by hmuranty** [comment]
I tried to guess Q and P (in this part I and N were not needed)
I used
Q <- length(levels(phenos$year))
P <- ncol(genos)

here are the error messages after trying to execute gs3
system.time(execGs3(config.file, stdouterr.file))
utilisateur     système      écoulé 
          0           0           0 
Warning message:
running command '"gs3.exe" C:/Users/HÃ©lÃ¨ne Muranty/Documents/SelGen/FruitSelgen/travail_Angers/config_gs3_vce.txt' had status 1 

> stdouterr <- readLines(stdouterr.file)
> Error in file(con, "r") : cannot open the connection
> In addition: Warning message:
> In file(con, "r") :
>   cannot open file 'C:/Users/Hélène Muranty/Documents/SelGen/FruitSelgen/travail_Angers/intro_stdouterr_gs3.txt': No such file or directory

perhaps I should try in a working directory without accents !

**Comment by timflutre** [comment]
```
perhaps I should try in a working directory without accents !
```

ah, yes ;)

**Comment by hmuranty** [comment]
That's it: using the working directory
C:/Users/Helene-ADMIN/Documents/FruitSelgen

I did not get error messages

> system.time(execGs3(config.file, stdouterr.file))
> utilisateur     système      écoulé 
>        0.00        0.02        0.33 
> stdouterr <- readLines(stdouterr.file)

**Comment by timflutre** [comment]
ok, good, that was it

I hope now that installing with `build_vignette=TRUE` will work.

**Comment by hmuranty** [comment]
Unfortunately, installing with build_vignette=TRUE doesn't work.

But I obtained a "fort.6" file in my working directory (fort.6 is the log file from gs3) ending with 
               |-------- STOP -------------------------------|
                | more animals in data than in genotype       |
                | animals with no genotype cannot be analysed |
                | the program will  stop                      |
                ----------------------------------------------|

I should probably also update my version of gs3.

**Comment by timflutre** [comment]
Ah sorry again, I should have told you earlier (in fact it's indicated in the vignette...): one should use a version of GS3 at least as recent as January 6, 2016 (Andrés had to do a small fix in order for the vignette to work).

**Comment by hmuranty** [comment]
I just downloaded a "new" version of gs3 for windows at
http://snp.toulouse.inra.fr/~alegarra/gs3.exe
and still obtain the same error message when trying to install with build_vignettes=TRUE
(and the same ending of the fort.6 file when executing the other code after installing with build_vignettes = FALSE)

How can I check if it's the new version ?

**Comment by timflutre** [comment]
On January 6, Andrés told me: "Les versions dans le web genoweb.toulouse.inra.fr/~alegarra sont corrigees".

To know if he also updated the Windows binary (and not only the Linux one), you can open the stdouterr.file and look at the date just below the 3rd line of dashes. For me, it's indicated "08/01/2016", as shown below:

```
 -----------------------
 --        GS3        --
 2.4.0               
 -- with Bayesian Lasso --
 -----------------------
 Copyright (c) A.Legarra 
  A. Ricard, O. Filangi
     INRA, FRANCE
 08 May 2014         

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.
     You should have received a copy of the GNU General Public License
     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ----------------------
 08/01/2016 00:14:28
```

**Comment by hmuranty** [comment]
I downloaded again gs3 from genoweb.toulouse.inra.fr/~alegarra instead of http://snp.toulouse.inra.fr/%7Ealegarra/gs3.exe. It had the same size (so probably the same).

I still obtain the same error message when trying to install with build_vignettes=TRUE
and the same ending of the fort.6 file when executing the other code after installing with build_vignettes = FALSE.
And the date in the fort.6 file is 

---

 --        GS3        --
 2.4.0  
 -- with Bayesian Lasso --

---

 Copyright (c) A.Legarra 
  A. Ricard, O. Filangi
     INRA, FRANCE
 08 May 2014         

```
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

---

 08/01/2016 17:04:29

It seems to be the date-hour of execution rather than the date-hour of compilation.

**Comment by timflutre** [comment]
Ok, I will see with Andrés then, and will let you know.

**Comment by timflutre** [comment]
Andrés Legarra just told me that he updated the Windows version downloadable on his [website](http://genoweb.toulouse.inra.fr/~alegarra/). Could you check if building the vignette now works on your machine?

**Comment by hmuranty** [comment]
After downloading again from Andres website, I could obtain the vignette. Ouf !

**Comment by timflutre** [comment]
great, thanks!
