### ISSUE TITLE
Update GS3 manual link

### ISSUE THREAD

**Issue by Atrebas** [timflutre/rgs3#13]
It's seems that the GS3 manual at http://genoweb.toulouse.inra.fr/~alegarra/gs3_folder/ is not up-to-date (May 2014). The github repository contains a more recent version (Nov. 2016).
The link in the rgs3 vignette should probably therefore be modified to:
https://github.com/alegarra/gs3/blob/master/manual/manualgs3_6.pdf
or
https://github.com/alegarra/gs3/raw/master/manual/manualgs3_6.pdf
for a direct download.

**Comment by timflutre** [comment]
Thanks, I will try to make this clearer in the vignette. But this is complicated by the fact that there is a disconnect between [here](http://genoweb.toulouse.inra.fr/~alegarra/gs3_folder/) (with old binaries and manual) and the GS3 [GitHub repo](https://github.com/alegarra/gs3) which provides no binary but a more recent version of the manual.

**Comment by timflutre** [comment]
Fixed by commit [532e697](https://github.com/INRA/rgs3/commit/532e697dd9d005f46ac9dbd09e8a9c752f5f8c2b).
