### ISSUE TITLE
R CMD build rgs3

### ISSUE THREAD

**Issue by GregorDall** [timflutre/rgs3#14]
Dear Timothée,

I was trying to download rgs3 from github but it failed, so I cloned the git repo and tried to build it myself on debian, Unfortunaltely, I am having problems. Do you think you could help? 
Best Gregor

R CMD build rgs3
* checking for file ‘rgs3/DESCRIPTION’ ... OK
* preparing ‘rgs3’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘crossval-rgs3.Rmd’ using rmarkdown
Quitting from lines 137-147 (crossval-rgs3.Rmd) 
Error: processing vignette 'crossval-rgs3.Rmd' failed with diagnostics:
isValidData(dat, NULL, col.id, col.trait, binary.trait) ist nicht TRUE
--- failed re-building ‘crossval-rgs3.Rmd’

--- re-building ‘intro-rgs3.Rmd’ using rmarkdown
Quitting from lines 308-311 (intro-rgs3.Rmd) 
Error: processing vignette 'intro-rgs3.Rmd' failed with diagnostics:
isValidData(x, inds, col.id, col.traits, binary.traits) ist nicht TRUE
--- failed re-building ‘intro-rgs3.Rmd’

SUMMARY: processing the following files failed:
  ‘crossval-rgs3.Rmd’ ‘intro-rgs3.Rmd’

Fehler: Vignette re-building failed.
Ausführung angehalten

**Comment by timflutre** [comment]
Dear Gregor,
I do not have time unfortunately to deal with that. But you may try to install the package without building the vignette (see [here](https://stackoverflow.com/questions/62465597/cant-disable-vignette-build-when-using-devtools)) and, afterwards, execute the vignette Rmd line by line to try to understand what is happening. Sorry for that!
Timothée

**Comment by GregorDall** [comment]
Dear Timothée,

Thank you for the quick response, I wasn't aware of the option to build the package without vignettes. I used R CMD build --no-vignettes rgs3, which seems to have worked. 

Gregor
