### ISSUE TITLE
handling missing data in writeDataForGs3 and writeGenosForGs3

### ISSUE THREAD

**Issue by hmuranty** [timflutre/rgs3#2]
I found a problem in the way missing data are handled in writeDataForGs3: if the data.frame with the phenotypic data has several columns before the trait of interest and these columns contain missing data, for the moment writeDataForGs3 will not transform them into -9999 and this will prevent reading data further by gs3. I had a phenotypic dataset with a missing data in the second trait at the 6th line, and when I asked for analysis of the third trait, only 5 records were read.

Concerning writeGenosForGs3, as gs3 can work with missing data in the genotypic data, and these have to be coded as "5", writeGenosForGs3 should accept values of 5 in the matrix of genotypic data.
So the stopping rules at the beginning should be
stopifnot(is.matrix(x), all(x %in% c(0, 1, 2, 5)), !is.null(rownames(x)), 
        is.vector(inds), is.numeric(inds), !is.null(names(inds)), 
        all(inds == 1:length(inds)), all(rownames(x) %in% names(inds)))

Hope this helps !

Hélène

**Comment by timflutre** [comment]
Thanks for the feedback! I'll try to fix it as soon as possible.

**Comment by timflutre** [comment]
1. The current `writeDataForGs3` function already replaces `NA` by `-9999` for continuous trait and `0` for binary trait. Do you mean that it should also replace `NA` by `-9999` for covariate(s)?
2. For `writeGenosForGs3`, I changed the code into `all(x %in% c(0,1,2,NA,5))`.

**Comment by hmuranty** [comment]
I mean that |writeDataForGs3| should also replace NA by -9999 for other 
trait(s) in the dataset, either used as covariate(s) or not used at all 
but present for convenience because gs3 stops reading the file if it 
encounters characters, but without stopping the run.

For writeGenosForGs3, I think the change should be OK.

Hélène

**Comment by timflutre** [comment]
I updated the repo with a fix (as well as others improvements). I had to change some options given to `writeDataForGs3`, so you will have to update your code. See the help with `?writeDataForGs3`. If this solves your problem, you can close this issue.

**Comment by hmuranty** [comment]
I couldn't see which "options" in writeDataforGs3 were changed (it seems that the input variables are the same) but I think the code is OK. Thanks !

**Comment by timflutre** [comment]
The changes are the following: `col.trait` was renamed into `col.traits`, and `binary.trait` into `binary.traits`. This is because GS3 expects missing values to be coded as `-9999` for continuous traits and covariables, and `0` for binary traits (at least according to the [manual](http://snp.toulouse.inra.fr/~alegarra/manualgs3_last.pdf#page=18)).
