### ISSUE TITLE
binary.traits and handling of missing data in writeDataForGs3

### ISSUE THREAD

**Issue by hmuranty** [timflutre/rgs3#3]
In writeDataForGs3, the default value for binary.traits as only one value, but if there are missing data, binary.traits is expected to be a vector of length the number of columns of x because there is a test on binary.traits[c] with c in 1:ncol(x).

However, at the beginning there is a test on length(binary.traits) == length(col.traits) so length(binary.traits) cannot be ncol(x)

I think replacing
                if (binary.traits[c]) {
by
                if (binary.traits[which(c == col.traits)]) {
 should work.

Hélène

**Comment by timflutre** [comment]
Fixed with commit https://github.com/timflutre/rgs3/commit/9fe31f277fdaf513504b49c5ad44a639fb69d6a8. A test was added.
